import { Product, AdminSettings } from './types';

export const DEMO_PRODUCTS: Product[] = [
  // MEN'S SHOES
  {
    id: 'm-shoe-1',
    name: "Classic Men's Leather Loafer",
    category: 'Shoes',
    gender: 'Men',
    brand: 'Elite Premium',
    description: 'Elegant leather loafers designed for comfort and style. Perfect for both formal and semi-formal occasions.',
    price: 45000,
    sku: 'ELT-M-SH-001',
    images: ['https://images.unsplash.com/photo-1533867617858-e7b97e060509?q=80&w=800&auto=format&fit=crop'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    colors: ['Black', 'Brown'],
    stockQuantity: 15,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'm-shoe-2',
    name: 'Premium Casual Sneaker',
    category: 'Shoes',
    gender: 'Men',
    brand: 'Elite Active',
    description: 'Versatile sneakers for the modern man. Features a breathable mesh and durable sole.',
    price: 35000,
    sku: 'ELT-M-SH-002',
    images: ['https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=800&auto=format&fit=crop'],
    sizes: ['40', '41', '42', '43', '44'],
    colors: ['White', 'Grey', 'Black'],
    stockQuantity: 20,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // WOMEN'S SHOES
  {
    id: 'w-shoe-1',
    name: "Elegant Women's Flat Shoe",
    category: 'Shoes',
    gender: 'Women',
    brand: 'Elite Grace',
    description: 'Chic and comfortable flat shoes that complement any outfit from day to night.',
    price: 25000,
    sku: 'ELT-W-SH-001',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop'],
    sizes: ['37', '38', '39', '40', '41'],
    colors: ['Beige', 'Black', 'Red'],
    stockQuantity: 12,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // BAGS
  {
    id: 'w-bag-1',
    name: "Classic Women's Handbag",
    category: 'Bags',
    gender: 'Women',
    brand: 'Elite Luxe',
    description: 'Spacious and stylish handbag crafted from premium synthetic leather. Features multiple compartments.',
    price: 40000,
    sku: 'ELT-W-BG-001',
    images: ['https://images.unsplash.com/photo-1584917033904-493bb3c3ce15?q=80&w=800&auto=format&fit=crop'],
    sizes: ['Medium'],
    colors: ['Black', 'Tan', 'Navy'],
    stockQuantity: 8,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'm-bag-1',
    name: "Men's Business Backpack",
    category: 'Bags',
    gender: 'Men',
    brand: 'Elite Pro',
    description: 'Professional backpack with a dedicated laptop sleeve and ergonomic design for daily commute.',
    price: 30000,
    sku: 'ELT-M-BG-001',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop'],
    sizes: ['Large'],
    colors: ['Black', 'Charcoal'],
    stockQuantity: 10,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // CLOTHES
  {
    id: 'm-cloth-1',
    name: "Classic Men's Shirt",
    category: 'Clothes',
    gender: 'Men',
    brand: 'Elite Formal',
    description: 'Crisp cotton shirt with a perfect fit. Ideal for office wear and special occasions.',
    price: 20000,
    sku: 'ELT-M-CL-001',
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=800&auto=format&fit=crop'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Light Blue'],
    stockQuantity: 25,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'w-cloth-1',
    name: "Elegant Women's Dress",
    category: 'Clothes',
    gender: 'Women',
    brand: 'Elite Style',
    description: 'Flowy and elegant dress that celebrates femininity. Perfect for both casual and formal outings.',
    price: 35000,
    sku: 'ELT-W-CL-001',
    images: ['https://images.unsplash.com/photo-1539008835657-9e8e9680c956?q=80&w=800&auto=format&fit=crop'],
    sizes: ['S', 'M', 'L'],
    colors: ['Floral', 'Solid Green', 'Black'],
    stockQuantity: 10,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // CANVAS FOOTWEAR
  {
    id: 'canvas-1',
    name: "Classic Unisex Canvas",
    category: 'Canvas',
    gender: 'Unisex',
    brand: 'Elite Canvas',
    description: 'Durable and stylish canvas shoes for everyday wear.',
    price: 15000,
    sku: 'ELT-UN-CV-001',
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=800&auto=format&fit=crop'],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    colors: ['Black', 'White', 'Blue'],
    stockQuantity: 30,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // SCHOOL CHILDREN
  {
    id: 'school-1',
    name: "Children's School Shoes",
    category: 'School Children',
    gender: 'Unisex',
    brand: 'Elite Kids',
    description: 'High-quality, durable school shoes for children. Designed to withstand daily school activities.',
    price: 12000,
    sku: 'ELT-K-SH-001',
    images: ['https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=800&auto=format&fit=crop'],
    sizes: ['30', '31', '32', '33', '34', '35'],
    colors: ['Black'],
    stockQuantity: 50,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // SPORT SHOES
  {
    id: 'sport-1',
    name: "Elite Performance Runner",
    category: 'Sport Shoes',
    gender: 'Unisex',
    brand: 'Elite Sport',
    description: 'Lightweight and responsive running shoes for maximum performance and comfort.',
    price: 28000,
    sku: 'ELT-UN-SP-001',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
    colors: ['Red', 'Blue', 'Neon'],
    stockQuantity: 25,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // PHONES
  {
    id: 'phone-1',
    name: "Flagship Smartphone Pro",
    category: 'Phones',
    gender: 'Unisex',
    brand: 'Elite Tech',
    description: 'Cutting-edge smartphone with a stunning OLED display, pro-grade camera system, and all-day battery life.',
    price: 850000,
    sku: 'ELT-PH-001',
    images: ['https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?q=80&w=800&auto=format&fit=crop'],
    sizes: ['128GB', '256GB', '512GB'],
    colors: ['Midnight', 'Starlight', 'Sierra Blue'],
    stockQuantity: 15,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'phone-2',
    name: "Elite Performance Plus",
    category: 'Phones',
    gender: 'Unisex',
    brand: 'Elite Tech',
    description: 'High-performance smartphone designed for power users. Features ultra-fast processing and crystal clear display.',
    price: 620000,
    sku: 'ELT-PH-002',
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800&auto=format&fit=crop'],
    sizes: ['128GB', '256GB'],
    colors: ['Black', 'Graphite'],
    stockQuantity: 20,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // LAPTOPS
  {
    id: 'laptop-1',
    name: "Elite Ultrabook Air",
    category: 'Laptops',
    gender: 'Unisex',
    brand: 'Elite Tech',
    description: 'Thin, light, and powerful ultrabook for professionals on the go. High-resolution Retina display and silent performance.',
    price: 1200000,
    sku: 'ELT-LP-001',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop'],
    sizes: ['8GB RAM / 256GB', '16GB RAM / 512GB'],
    colors: ['Space Grey', 'Silver'],
    stockQuantity: 8,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'laptop-2',
    name: "Pro Creative Workstation",
    category: 'Laptops',
    gender: 'Unisex',
    brand: 'Elite Tech',
    description: 'Heavy-duty laptop designed for designers and developers. Top-tier graphics and high-speed processing.',
    price: 2400000,
    sku: 'ELT-LP-002',
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=800&auto=format&fit=crop'],
    sizes: ['16GB RAM / 1TB', '32GB RAM / 1TB'],
    colors: ['Space Grey'],
    stockQuantity: 5,
    status: 'Published',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  }
];

export const INITIAL_SETTINGS: AdminSettings = {
  businessName: 'Elite Collections',
  phone: '09157364936',
  whatsappNumber: '09157364936',
  email: 'bethelbusiness556@gmail.com',
  description: 'Elite Collections is a premium business committed to providing quality electronics, shoes, bags and clothing for men, women and children.',
  address: 'Lagos, Nigeria',
  deliveryFee: 2000,
  vision: 'To build a trusted fashion brand known for quality, style, excellent customer service and accessibility.',
  mission: 'To provide quality fashion products while creating a simple, convenient and trustworthy shopping experience for every customer.',
  businessHours: 'Mon - Sat: 9am - 6pm',
};
